require 'fileutils'
require 'rake/clean'

BOOK = "book"
BOOK_PDF = BOOK+".pdf"
BOOK_EPUB = BOOK+".epub"
CONFIG_FILE = "config.yml"

def build(mode, chapter)
  sh "review-compile --target=#{mode} --footnotetext --stylesheet=style.css #{chapter} > tmp"
  mode_ext = {"html" => "html", "latex" => "tex",
              "idgxml" => "xml", "inao" => "inao"}
  FileUtils.mv "tmp", chapter.gsub(/re\z/, mode_ext[mode])
end

def build_all(mode)
  sh "review-compile --all --target=#{mode} --footnotetext --stylesheet=style.css"
end

def rename_image(content, newfile, filename, imagename, imageext)
  bsname = File.basename(newfile,".md")
  if bsname == filename
    n = 0
    content.gsub!(/#{imagename}\.#{imageext}/) do |i|
      n+=1
      if n > 1
        "#{imagename}_#{n}.#{imageext}"
      else
        "#{imagename}.#{imageext}"
      end
    end
  end
end

def conv_review
  FileUtils.mkdir_p("md")
  Dir.glob("../_posts/*.md") do |file|
    content = File.read(file)
    content.gsub!(/\A.*?^# /m, "# ")
    ### 無理やり変換
    content.gsub!(/^コラム：([^\n]*)\n([^\n]*)\n\n/m){ "====[column] #{$1}\n\n#{$2}\n\n====[/column]\n"}
##    content.gsub!(/^コラム：([^\n]*)\n([^\n]*)\n\n/m){ "//note[#{$1}]{\n\n#{$2}\n\n//}\n"}
    newfile = file.sub(/..\/_posts/, "md")

    rename_image(content, newfile, "2014-06-01-smallest-app", "time_jst", "png")
    rename_image(content, newfile, "2014-06-01-smallest-app", "rails_app_request_to_response", "png")
    rename_image(content, newfile, "2014-07-01-crud", "index_flow", "png")
    rename_image(content, newfile, "2014-07-01-crud", "index_page_with_data", "png")
    rename_image(content, newfile, "2014-08-01-new-create", "create-controller", "png")
    rename_image(content, newfile, "2014-09-01-model", "create-overview", "png")

    File.open(newfile, "w") do |f|
      f.write(content)
    end
  end

  Dir.glob("./md/*.md") do |file|
    newfile = file.gsub(/\.md/, ".re")
    newfile.gsub!(/md\//, "../review/")
    newfile.gsub!(/201\d-\d\d-\d\d-/, "")
    cline = "md2review --render-enable-cmd --parse-no-intra-emphasis #{file} > #{newfile}"
    p cline
    system(cline)
  end

  Dir.glob("../assets/**/*.png") do |file|
    newfile = file.gsub(/assets\//, "../review/images/")
    newfile.downcase!
    newfile.gsub!(/kn\//, "")
    dir = File.dirname(newfile)
    FileUtils.mkdir_p(dir)
    FileUtils.cp(file, newfile)
  end

  FileUtils.cp("../assets/my-first-web-app/welcome_rails.png", "../review/images/smallest-app/")
#  FileUtils.cp("../assets/smallest-app/time_now.png", "../review/images/smallest-app/time_now_2.png")
  FileUtils.cp("../assets/smallest-app/kn/rails_app_request_to_response.png", "../review/images/smallest-app/rails_app_request_to_response_2.png")
  FileUtils.cp("../assets/crud/kn/index_flow.png", "../review/images/crud/index_flow_2.png")
  FileUtils.cp("../assets/crud/index_page_with_data.png", "../review/images/crud/index_page_with_data_2.png")
  FileUtils.cp("../assets/new-create/kn/create-controller.png", "../review/images/new-create/create-controller_2.png")
  FileUtils.cp("../assets/model/kn/create-overview.png", "../review/images/model/create-overview_2.png")
end

task :default => :all

desc "build html (Usage: rake build re=target.re)"
task :html do
  if ENV['re'].nil?
    puts "Usage: rake build re=target.re"
    exit
  end
  build("html", ENV['re'])
end

desc "build all html"
task :html_all do
  build_all("html")
end

desc "build all html"
task :conv_review do
  conv_review()
end

desc 'generate PDF and EPUB file'
task :all => [:conv_review, :pdf, :epub]

desc 'generate PDF file'
task :pdf => BOOK_PDF

desc 'generate EPUB file'
task :epub => BOOK_EPUB

SRC = FileList['*.re'] + [CONFIG_FILE]

file BOOK_PDF => SRC do
  FileUtils.rm_rf [BOOK_PDF, BOOK, BOOK+"-pdf"]
  sh "review-pdfmaker #{CONFIG_FILE}"
end

file BOOK_EPUB => SRC do
  FileUtils.rm_rf [BOOK_EPUB, BOOK, BOOK+"-epub"]
  sh "review-epubmaker #{CONFIG_FILE}"
end

CLEAN.include([BOOK, BOOK_PDF, BOOK_EPUB, BOOK+"-pdf", BOOK+"-epub"])
